# Generated by Django 5.2.5 on 2025-09-25 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userprofile_full_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
